@startuml
'https://plantuml.com/activity-diagram-beta

start
:User executes add command;
if () then ([duplicate internship])
    :Displays error message;
 else ([else])
    :Add internship to list;
    :View panel displays new internship;
 endif
stop

@enduml